# Generated by Django 3.0.2 on 2020-01-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('endereço', models.CharField(max_length=100)),
            ],
        ),
    ]
